version: "3.9"

services:
    swagger-ui:
        build:
            context: ./
            dockerfile: ./Dockerfile.swagger
        ports:
        - 8000:8000 ## Remove for deployment
        volumes:
        - ./api/spec:/api/spec ## Remove for deployment
