version: "3"

services:
    swagger-ui:
        command: ["swagger-ui-watcher", "--host", "0.0.0.0", "--no-open", "./spec/_root.yml"]
        image: swagger-viewer
        ports:
        - 8000:8000
        volumes:
        - ./api/spec:/api/spec
